name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Shared Hosting via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 21098
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
          cd public_html
          git pull origin main
          composer install --prefer-dist --no-dev --optimize-autoloader
          php artisan optimize
          php artisan config:clear
          php artisan cache:clear
